"""
Render Jinja2 spec templates into spec files.

Reads every *.specd.md file from a templates directory, renders each
as a Jinja2 template, and writes the output to a specs directory with
the .specd.md suffix replaced by .md.
"""

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

GENERATED_MARKER = "<!-- generated by specd -- do not edit -->"


def render_all(templates_dir, specs_dir):
    """
    Render all *.specd.md templates in templates_dir to specs_dir.

    Output filenames have .specd.md replaced with .md. Each output file
    is prefixed with a generated-file marker comment.
    """
    templates_dir = Path(templates_dir)
    specs_dir = Path(specs_dir)

    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        keep_trailing_newline=True,
        lstrip_blocks=True,
        trim_blocks=True,
    )

    templates = sorted(templates_dir.glob("*.specd.md"))

    if not templates:
        print("No *.specd.md templates found in templates/")
        return

    for template_path in templates:
        template = env.get_template(template_path.name)
        rendered = template.render()
        output_name = template_path.name.removesuffix(".specd.md") + ".md"
        output_path = specs_dir / output_name
        output_content = GENERATED_MARKER + "\n\n" + rendered
        output_path.write_text(output_content, encoding="utf-8")
        print(f"  {template_path.name} -> specs/{output_name}")
