"""
Tests for spec rendering behavior: file naming, header, Jinja evaluation, and errors.
"""

import subprocess
import sys
from pathlib import Path

SPECD = [sys.executable, "-m", "specd.cli"]


def _run(*args, cwd=None):
    """Run specd with the given arguments and return CompletedProcess."""
    return subprocess.run(
        SPECD + list(args),
        capture_output=True,
        text=True,
        cwd=str(cwd) if cwd else None,
    )


def _setup(tmp_path):
    """Create and return (templates_dir, specs_dir) under tmp_path."""
    templates_dir = tmp_path / "templates"
    specs_dir = tmp_path / "specs"
    templates_dir.mkdir()
    specs_dir.mkdir()
    return templates_dir, specs_dir


class TestOutputFileNaming:

    def test_scope_name_preserved_in_output_filename(self, tmp_path):
        """
        Spec: A template named in the form <scope>.specd.md is rendered into the specs directory with the name <scope>.md. [render.md]
        """
        templates_dir, specs_dir = _setup(tmp_path)
        (templates_dir / "myscope.specd.md").write_text("# My scope\n", encoding="utf-8")

        _run("render", "-t", str(templates_dir), "-s", str(specs_dir))

        assert (specs_dir / "myscope.md").exists()
        assert not (specs_dir / "myscope.specd.md").exists()


class TestOutputFileHeader:

    def test_output_file_starts_with_generated_header(self, tmp_path):
        """
        Spec: Every output file starts with `<!-- generated by specd -- do not edit -->\\n\\n` [render.md]
        """
        templates_dir, specs_dir = _setup(tmp_path)
        (templates_dir / "foo.specd.md").write_text("# Foo\n", encoding="utf-8")

        _run("render", "-t", str(templates_dir), "-s", str(specs_dir))

        content = (specs_dir / "foo.md").read_text(encoding="utf-8")
        assert content.startswith("<!-- generated by specd -- do not edit -->\n\n")


class TestJinjaRendering:

    def test_jinja_syntax_evaluated(self, tmp_path):
        """
        Spec: All jinja syntax in the template is evaluated in the rendered spec [render.md]
        """
        templates_dir, specs_dir = _setup(tmp_path)
        (templates_dir / "foo.specd.md").write_text(
            "# Result\n\n{{ 1 + 1 }}\n", encoding="utf-8"
        )

        _run("render", "-t", str(templates_dir), "-s", str(specs_dir))

        content = (specs_dir / "foo.md").read_text(encoding="utf-8")
        assert "2" in content
        assert "{{" not in content

    def test_plain_template_rendered_with_header_only_added(self, tmp_path):
        """
        Spec: A template with no jinja syntax is rendered into a spec with identical content + the "generated by specd" comment [render.md]
        """
        templates_dir, specs_dir = _setup(tmp_path)
        plain_content = "# My Spec\n\n- item one\n- item two\n"
        (templates_dir / "foo.specd.md").write_text(plain_content, encoding="utf-8")

        _run("render", "-t", str(templates_dir), "-s", str(specs_dir))

        content = (specs_dir / "foo.md").read_text(encoding="utf-8")
        header = "<!-- generated by specd -- do not edit -->\n\n"
        assert content == header + plain_content


class TestJinjaErrors:

    def test_jinja_error_prints_to_stderr_and_exits_1(self, tmp_path):
        """
        Spec: When Jinja2 errors arise in rendering they are allowed to propagate and print to stderr, then it exits code 1 [render.md]
        """
        templates_dir, specs_dir = _setup(tmp_path)
        (templates_dir / "bad.specd.md").write_text(
            "# Bad\n\n{{ unclosed_block\n", encoding="utf-8"
        )

        result = _run("render", "-t", str(templates_dir), "-s", str(specs_dir))

        assert result.returncode == 1
        assert result.stderr
